### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by SlySven** [manisandro/GdbCrashHandler#4]
Is this project only licenced to GPL **3.0** terms or does it have the more useful *(or, at the user's discretion, any later version)*? I note that a sample (looking at just one CPP source file) does include that addition but that is ***not being reflected in the COPYING file or the GitHub licence display***.

As it happens I am looking to include this in a GPL 2.0 or later project and as it is the licence here will force us to up our requirement to 3.0 - I just want to know that we will not have to lock it to just that version should the GPL ever get revised...

**Comment by manisandro** [comment]
No you won't have to lock to GPLv3, as whatever revised license stays compatible. I.e. as per  https://fedoraproject.org/wiki/Licensing:Main#GPL_Compatibility_Matrix

**Comment by SlySven** [comment]
Looking at the source code which *is* marked as GPL3.0 or later I can see that yeah - I can copy this project into our GPL2.0 or later and the composite will be GPL3.0 or later. What is confusing is that neither the COPYING text (nor the GitHub licence declaration) - includes anything about the *or, at the user's option, any later version*... OTOH our (the Mudlet Makers) project **[Mudlet](https://github.com/Mudlet/Mudlet.git)** also has this issue with respect to Git-Hub's licence display!

**Comment by manisandro** [comment]
This just means that the code is released under the GPLv3 license, and the COPYING text is just the full verbatim license text, as referenced by the source files. The license header in the source files also state that if you are free to see the code licensed according to the terms of any later GPL version. (The github license display probably just parses any COPYING or LICENSE etc it finds).

**Comment by SlySven** [comment]
Yeah - I have raised the licence display issue with GH - wait to hear what they say. It looks like our project can live with it so closing this issue.
